POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salane"
}
###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "naikou",
    "name": "nico",
    "password": "fritz"
}
###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "petteri",
    "name": "petteri",
    "password": "kuono"
}