POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Third blog", 
    "number": "Paavo P",
    "url": "random url 2",
    "likes": 10000
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "ANOTHER blog",
    "number": "123",
    "author": "PETTERI PTTEER",
    "url": "123",
    "userId": "652e5daf9a74a47381b376cb",
    "likes": 145
}
###
// creating blog using login token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5haWtvdSIsImlkIjoiNjUyZjFhODVkOWFiZjhjNTg0ZDUyNjZhIiwiaWF0IjoxNjk4MTQ1ODc5fQ.5A4BVAEEigW6YTNoPmazQkhgI5RY-YWdiyP8Lh_kvwM

{
    "title": "Test blog that i delete before submit",
    "number": "12311",
    "author": "123",
    "url": "naik123ou.co123123123123m",
    "likes": 1451212
}
