POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "naikou",
    "password": "fritz"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "petteri",
    "password": "kuono"
}